import { useState } from 'react'
import type { Recommendation } from '../../api/types'
import { ArrowUpRight, Calendar, Check, ChevronDown, Clock, Sparkle } from '../common/Icons'
import { TinyTag } from '../common/Badge'

export function RecommendationCard({ recommendation, onComplete, completing }: { recommendation: Recommendation; onComplete: () => void; completing: boolean }) {
  const [expanded, setExpanded] = useState(true)
  return <article className="recommendation-card"><div className="rec-topline"><TinyTag tone="lime">Recommended next step</TinyTag>{recommendation.rank !== undefined && <span className="match-score">Step <strong>{recommendation.rank}</strong></span>}</div><div className="rec-title-row"><div><h3>{recommendation.title}</h3>{recommendation.description && <p>{recommendation.description}</p>}{recommendation.explanation && !recommendation.description && <p>{recommendation.explanation}</p>}</div><div className="rec-icon"><Sparkle size={20} /></div></div><div className="rec-meta">{recommendation.type && <span><span className="meta-symbol">◈</span>{recommendation.type.replace('_', ' ')}</span>}{recommendation.duration_hours !== undefined && <span><Clock size={14} />{recommendation.duration_hours} hours</span>}{recommendation.next_session && <span><Calendar size={14} />{formatDate(recommendation.next_session)}</span>}{recommendation.format && <span>{recommendation.format}</span>}</div><button className="explain-toggle" onClick={() => setExpanded(!expanded)}><span><Sparkle size={15} /> Why this activity?</span><ChevronDown size={15} /></button>{expanded && <div className="rec-explanation"><div className="reason-list">{recommendation.reasons.length ? recommendation.reasons.map((reason) => <div className="reason" key={reason}><span className="reason-check"><Check size={13} /></span><span>{reason}</span></div>) : <div className="reason">{recommendation.explanation || 'The backend did not return structured evidence for this activity.'}</div>}</div>{recommendation.skill_impacts.length > 0 && <div className="impact-box"><div className="impact-label">PREDICTED IMPACT</div>{recommendation.skill_impacts.map((impact) => <div className="impact-row" key={impact.skill_id}><span>{impact.name}</span><strong>{impact.before} <i>→</i> {impact.after}</strong><small>Required {impact.required}</small></div>)}</div>}</div>}<div className="rec-footer"><span className="event-id">{recommendation.event_id}</span><button className="complete-button" onClick={onComplete} disabled={completing}><span className={completing ? 'button-spinner' : ''}>{completing ? 'Updating…' : 'Complete activity'}</span>{!completing && <ArrowUpRight size={15} />}</button></div></article>
}

function formatDate(value: string) { return new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric' }).format(new Date(value)) }
